name: Java CI

on:
  workflow_dispatch:
    inputs:
      my_parameter:
        description: 'A custom parameter'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'cat(remotes::system_requirements("ubuntu", "20.04"), sep = "\n")')
        # run: mvn exec:java -Dexec.mainClass="crawler.WebInterface" -Dexec.args="${current.project.path}/database ${current.project.path}/www" -f ${current.project.path} pom.xml

    # Add a condition here to determine whether to run the job or not
    if: ${{ github.ref == 'refs/heads/main' }}
